name: build

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.25, 1.26]
    name: Tests ${{ matrix.os }} @ Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Source
        uses: actions/checkout@v6.0.2
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6.2.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Display Go version
        run: go version
      - name: Test
        run: go test -v -coverprofile=cover.out ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jub0bs/errutil
  benchmark:
    # Mostly to compare allocations;
    # measurements of execution speed in GitHub Actions are unreliable.
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.25, 1.26]
    name: Benchmark comparison ${{ matrix.os }} @ Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Code (new)
        uses: actions/checkout@v6.0.2
        with:
          path: new
          fetch-depth: '0' # fetch all history for all branches and tags
      - name: Retrieve latest tag
        id: latest-tag
        run: |
          cd new
          echo "LATEST_TAG=$(git for-each-ref --sort=-version:refname --format='%(refname:lstrip=2)' --count=1 refs/tags)" >> "$GITHUB_OUTPUT"
      - name: Check out Code (previous)
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ steps.latest-tag.outputs.LATEST_TAG }}
          path: previous
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6.2.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest
      - name: Run Benchmark (previous)
        run: |
          cd previous
          go test -run '^$' -bench '^BenchmarkAll$' -count 10 . -benchtime 10000x > bench.out
      - name: Run Benchmark (new)
        run: |
          cd new
          go test -run '^$' -bench '^BenchmarkAll$' -count 10 . -benchtime 10000x > bench.out
      - name: Run benchstat (old vs. new)
        run: |
          benchstat previous/bench.out new/bench.out
      - name: Run benchstat (errors.As vs. errutil.As)
        run: |
          benchstat -col "/impl@(errors.As errutil.As)"  new/bench.out
      - name: Run benchstat (errors.As vs. errutil.Find)
        run: |
          benchstat -col "/impl@(errors.As errutil.Find)" new/bench.out
      - name: Run benchstat (errutil.As vs. errutil.Find)
        run: |
          benchstat -col "/impl@(errutil.As errutil.Find)" new/bench.out
